# -*- coding: utf-8 -*-
"""LVADSUSR178_PriyadarshiniM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdsHtt11K3aUTOkGRWPdWIeAuFbLJDHq
"""

#Lab Section 1
#1. Commercial Property Management System

def area_calc():
  l= float(input("Enter length:"))
  w= float(input("Enter width:"))
  area= l*w
  print(f"The total area is {area} kmsq")
  if area <=500:
    print("Property Size: Small")
  if area >500 and area <1000:
    print("Property Size: Medium")
  if area > 1000:
    print("Property Size: Big")

area_calc()

#2. Integrated Health Management App
def bmi_calc():
  w= float(input("Enter your weight:"))
  h= float(input("Enter your height:"))
  bmi= round(w/(h**2))
  print(f"Your BMI is {bmi}")
  if bmi <=19:
    print("You are underweight! Start eating healthy foods!!")
  if bmi >20 and bmi <25:
    print("You are healthy! Enhance your routine!!")
  if bmi >25:
    print("You are overweight! Start working out!!")

bmi_calc()

#3. Educational Record System
d1={"name": "Alice", "age": 15, "grade": "A"}
d2={"name": "Bob", "age": 15, "grade": "C"}
d3={"name": "Charles", "age": 15, "grade": "B"}
#retrieving student records
print(d1,d2,d3)
#adding
d1["city"]= "Newyork"
print(d1)
#updating

#Lab Section 2
#4. Content Recommendation Engine

def cont_rec():
  age= int(input("Enter your age:"))
  if age <=12:
    cr= "Children"
    print(f"Based on {cr} content, you can watch Dora the Explorer!! ")
  if age >12 and age <20:
    cr= "Teen"
    print(f"Based on {cr} content, you can watch The Office!!")
  if age >21 and age < 50:
    cr= "Adult"
    print(f"Based on {cr} content, you can watch NDTV!!")
  if age> 51:
    cr="Senior"
    print(f"Based on {cr} content, you can watch National Geography!!")

cont_rec()

#5. Promotional Email Dispatcher

#6. Corporate Network Security System
pwd= "Qwerty@24"
ip= input("Enter password:")
if ip in pwd:
   print("Correct password")
if ip not in pwd:
   print("Wrong password. Retry again!")
   print(ip)

#7. Customer Feedback Analysis:
def survey():
  b =int(input("Enter rating for battery life for 5:"))
  s = int(input("Enter rating for storage for 5:"))
  d = int(input("Enter rating for durability for 5:"))
  avg_r= (b+s+d)/3
  print(f"The average score is {avg_r}")
  if avg_r<2:
    print("Thanks for your feedback. We will work towards improvement")
  if avg_r >2:
    print("Thanks for your valuable feedback. Glad that you liked our service")
survey()

#8. Content Moderation system
def comment_quality():
  c= ["a", "e","i","o","u"]
  comment= str(input("Enter comment:"))
  if comment in c:
    print("Good comment")
  else:
    print("Spam")
comment_quality()

#9.Automated Event reminder

#10. Robust financial calculator
def calc():
  amount=1000
  p= float(input("Enter the amount:"))
  i= float(input("Enter the interest:"))
  saving= (amount-p)
  loan= p*i
  print(f"Your savings is {saving}")
  print(f"You need to pay {loan}")

calc()

#11

#12 Data
def data():
  n1= int(input("Enter n1:"))
  n2= int(input("Enter n2:"))
  div= n1/n2
  print(f"Division of you numbers is {div}")
data()
try:
  div= n1/0
except ZeroDivisionError:
  print("n2 as 0 is not allowed")

#13

#14
myfile= open("C/log_file.txt",'r')

#15
script= ""