# -*- coding: utf-8 -*-
"""LVADSUSR178_PriyadarshiniM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4376-FiNzrIxNAQlB_fF431Q8GaCP49
"""

import numpy as np
import pandas as pd

d=pd.read_csv('/content/expenses.csv')

# d.head()
d.info()

#1.5 Tasks
#Handling missing values and outliers
d.isnull().sum()

d['bmi']=d['bmi'].fillna(d['bmi'].mean())

d.isnull().sum()

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(7,7))
sns.scatterplot(data=d, marker='o')
plt.title("Outliers in Expenses data")
plt.show()

#encoding categorical data
from sklearn.preprocessing import LabelEncoder
len=LabelEncoder()
d['sex']=len.fit_transform(d['sex'])
d['smoker']=len.fit_transform(d['smoker'])
d['region']=len.fit_transform(d['region'])
d.info()

#3.feature selection and data cleaning
# d.duplicated().sum()
d.drop_duplicates(inplace=True)

d.duplicated().sum()

x=d.drop(columns=['charges'])
y=d['charges']

#4.data splitting
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=10)

from sklearn.preprocessing import MinMaxScaler,StandardScaler
scaler = MinMaxScaler()

x_train=pd.DataFrame(scaler.fit_transform(x_train[list(x.columns)]),
                                    columns=x.columns)
x_test=pd.DataFrame(scaler.transform(x_test[list(x.columns)]),
                                    columns=x.columns)

#5.model development and training
model=LinearRegression()
model.fit(x_train, y_train)
pred=model.predict(x_test)

#6.model evaluation
from sklearn.metrics import mean_squared_error, r2_score
mse= mean_squared_error(pred, y_test)
rmse=mean_squared_error(pred, y_test, squared=False)
# rmse=np.sqrt(mse)
r2=r2_score(pred, y_test)
print(f"The R-squared score for the model is\n {r2}")
print(f"The RMSE for the model is\n {rmse}")

#1.6 Expected Outcome
#In the given scenario, linear regression is used for building a model that predicts the insurance charges
#for a particular financial sector. Here "charges" is considered as the dependent variable and others are
#taken to be independent variables.

import numpy as np
import pandas as pd

d=pd.read_csv('/content/booking.csv')

d.head()

d.info()

#2.5 Tasks
#Handling missing values and outliers
d.isnull().sum()

d['room type']=d['room type'].fillna(d['room type'].mode())
d['average price']=d['average price'].fillna(d['average price'].mean())

d.isnull().sum()

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(15,7))
sns.scatterplot(data=d, marker='o')
plt.title("Outliers in Expenses data")
plt.show()

#2.encoding categorical values
from sklearn.preprocessing import LabelEncoder
len=LabelEncoder()
d['Booking_ID']=len.fit_transform(d['Booking_ID'])
d['type of meal']=len.fit_transform(d['type of meal'])
d['room type']=len.fit_transform(d['room type'])
d['market segment type']=len.fit_transform(d['market segment type'])
d['date of reservation']=len.fit_transform(d['date of reservation'])
d['booking status']=len.fit_transform(d['booking status'])

d.info()

#3. feature selection and data cleaning
d.duplicated().sum()
# d.drop_duplicates(inplace=True)

x=d.drop(columns=['booking status'])
y=d['booking status']

#4. data splitting
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.3, random_state=10)

from sklearn.preprocessing import MinMaxScaler,StandardScaler
scaler = MinMaxScaler()

x_train=pd.DataFrame(scaler.fit_transform(x_train[list(x.columns)]),
                                    columns=x.columns)
x_test=pd.DataFrame(scaler.transform(x_test[list(x.columns)]),
                                    columns=x.columns)

#5. model development and training
model=LogisticRegression()
model.fit(x_train, y_train)
pred=model.predict(x_test)
# print(pred)

#6.Model evaluation
from sklearn.metrics import precision_score, accuracy_score, recall_score, f1_score, classification_report, confusion_matrix
ps=precision_score(pred, y_test)
ac=accuracy_score(pred, y_test)
re=recall_score(pred, y_test)
fs=f1_score(pred, y_test)
cr=classification_report(pred, y_test)
cm=confusion_matrix(pred, y_test)
print(f"Precision score:\n {ps}")
print(f"Accuracy score:\n {ac}")
print(f"Recall score:\n {re}")
print(f"F1-score:\n {fs}")
print(f"Classification report:\n {cr}")
print(f"Confusion matrix:\n {cm}")

#2.6 Expected outcome
#In the given scenario, logistic regression is used to build the model which predicts the booking status
#for a particular hotel. "booking status" is considered as the dependent variable and others are taken
#to be independent variables. For this model the accuracy score is 79% which indicates that the relation
#between the dependent and independent variables is highly correlated.